
version: 2

models:
  - name: terra_daily_blocks
    description: Daily terra blocks
    columns:
      - name: metric_date
        description: The date the metric was recorded
        tests:
            - not_null
      - name: tx_count
        description: The count of blocks produced on a particular day.

  - name: terra_daily_txs
    description: Daily terra transactions
    columns:
      - name: metric_date
        description: The date the metric was recorded
        tests:
            - not_null
      - name: tx_count
        description: The count of transactions generated on a particular day.
