version: 2

sources:
  - name: terra
    schema: terra
    tables:
      - name: blocks
      - name: transitions
      - name: transactions
      - name: msgs
      - name: msg_events
      - name: terra_validator_voting_power
      - name: udm_daily_balances_terra
      - name: udm_custom_fields_terra_tax_rate
  - name: polygon
    schema: polygon
    tables:
      - name: udm_events
      - name: events_emitted
      - name: transactions
  - name: ethereum
    schema: ethereum
    tables:
      - name: udm_events
      - name: events_emitted
      - name: transactions